# Common parameters
concurrency: true

# Tracker parameters
tracker:
  laser_cloud:
    concurrency_level: 2
    visualize_rviz: true
    max_cluster_size: 150 # default: 100
    min_cluster_size: 30 # default: 20
    tolerance: 0.04 # [m]
    scan_frame: "fusion_base"
    scan_topic: "cloud"
    #target_frame: "base_link"

  camera_cloud:
    concurrency_level: 2
    visualize_rviz: true
    max_cluster_size: 400 # default: 400
    min_cluster_size: 40 # default: 40
    tolerance: 0.06 # [m]
    scan_frame: "fusion_base"
    scan_topic: "/mynteye/points/data_raw"
    #target_frame: "base_link"


# Converter parameters
converter:
  concurrency_level: 2
  target_frame: "fusion_base"
  #subscription_topic: "your_topic"
  #transform_tolerance: 0.01 # default: 0.01 [m]
